version: '3'

services:
  books-frontend:
    build:
      context: frontend
      dockerfile: DockerfileFrontend
    restart: always
    container_name: books-frontend
    ports:
      - "8090:80"
    tty: true
    depends_on:
      - books-backend
  books-backend:
    build:
      context: backend
      dockerfile: DockerfileServer
    restart: always
    environment:
      - DB_HOST=books-db
      - DB_PORT=5432
      - DB_NAME=booksdb
      - DB_USER=booksdb
      - DB_PASSWORD=booksdb
    container_name: books-backend
    tty: true
    depends_on:
      - books-db
  books-db:
    image: postgres:10.3-alpine
    container_name: books-db
    ports:
      - "25432:5432"
    restart: always
    environment:
      - POSTGRES_DB=booksdb
      - POSTGRES_USER=booksdb
      - POSTGRES_PASSWORD=booksdb