version: '3'

services:
  books_frontend:
    build:
      context: frontend
      dockerfile: DockerfileFrontend
    restart: always
    container_name: books_frontend
    ports:
      - "8085:80"
    tty: true
    depends_on:
      - backend
  books_backend:
    build:
      context: backend
      dockerfile: DockerfileServer
    restart: always
    entrypoint:
      - DB_HOST=books_db
      - DB_PORT=5432
      - DB_NAME=booksdb
      - DB_USER=booksdb
      - DB_PASSWORD=booksdb
    container_name: books_backend
    tty: true
    depends_on:
      - db
  books_db:
    image: postgres:10.3-alpine
    container_name: books_db
    ports:
      - "25432:5432"
    restart: always
    environment:
      - POSTGRES_DB=booksdb
      - POSTGRES_USER=booksdb
      - POSTGRES_PASSWORD=booksdb