version: '3'

services:
  app:
    build:
      context: backend
      dockerfile: Dockerfile
    restart: always
    container_name: app_server
    ports:
      - "18080:8080"
    tty: true
    depends_on:
      - db
  db:
    image: postgres:10.3-alpine
    container_name: app_db
    ports:
      - "25432:5432"
    restart: always
    environment:
      - POSTGRES_DB=booksdb
      - POSTGRES_USER=booksdb
      - POSTGRES_PASSWORD=booksdb